1.Create a NumPy array a with values 1 through 9. Reshape the array to a 3x3 matrix.


In [2]:
import numpy as np
a = np.arange(1,10)
print(a.reshape(3,3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


 2.Create a NumPy array b with values 5 through 13. Reshape the array to a 3x3 matrix. 

In [3]:
import numpy as np
b= np.arange(5,14)
print(b.reshape(3,3))

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


3.Multiply the matrix a by the matrix b using the @ operator. 

In [4]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b= np.array([[5,6,7],
             [ 8,9,10],
             [11,12,13]])

result = a @ b
print(result)

[[ 54  60  66]
 [126 141 156]
 [198 222 246]]


4.Compute the dot product of the first row of a with the first column of b.

In [5]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b= np.array([[5,6,7],
             [ 8,9,10],
             [11,12,13]])
first_row_a =a[0,:]
first_colomn_b = b[:,0]
dot_product = np.dot(first_row_a,first_colomn_b )
print(dot_product)

54


 5.Compute the sum of all the elements in the matrix a. 

In [9]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
result = np.sum(a)
print(result)

45


6.Compute the product of all the elements in the matrix b. 

In [11]:

b= np.array([[5,6,7],
             [ 8,9,10],
             [11,12,13]])

result =np.prod(b)
print(result)

259459200


7.Create a 1D NumPy array c with values [1, 2, 3, 4, 5]. Use the np.insert() function to insert the value 0 at index 2.

In [17]:
c = np.array( [1, 2, 3, 4, 5])
c = np.insert(c,2,0)
print(c)

[1 2 0 3 4 5]


 8.Create a 1D NumPy array d with values [1, 2, 3, 4, 5]. Use the np.delete() function to delete the value at index 3.

In [19]:
d = np.array( [1, 2, 3, 4, 5])
d = np.delete(c,3)
print(d)

[1 2 0 4 5]


 9.Create a 2D NumPy array e with dimensions 3x4 and values 1 through 12. Use boolean indexing to select all elements greater than 5. 

In [24]:
e = np.arange(1,13).reshape(3,4)

five_up = (e > 5) | (e == 5)
print(five_up)


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


10.Create a 2D NumPy array f with dimensions 4x5 and values 1 through 20. Use fancy indexing to select the elements at positions (0,0), (1,2), and (2,4). 

In [26]:
f= np.arange(1,21).reshape(4,5)

elements = f[[0,1,2],[0,2,4]]

print(f"Array f:\n{f}")
print(f"Selected elements: {elements}")

Array f:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Selected elements: [ 1  8 15]


11.Create a 2D NumPy array a with dimensions 5x5 and values 0.5 in the diagonal and 0 elsewhere.

In [12]:
a= np.eye(5)*0.5
print(a)

[[0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5]]


12.Create a 3D NumPy array b with dimensions 3x3x3 and random integer values between 0 and 10.


In [13]:
b = np.random.randint(0,11,size = (3,3,3))
print(b)

[[[ 0  6  5]
  [ 6 10  8]
  [ 1  5  2]]

 [[ 1  0 10]
  [ 2  5  0]
  [ 2  6  0]]

 [[ 5  1  6]
  [ 8  7  1]
  [ 5  1  3]]]


13.Compute the mean of each row of the matrix b.


In [ ]:
b = np.array([[[ 0  6  5]
              [ 6 10  8]
              [ 1  5  2]]

             [[ 1  0 10]
              [ 2  5  0]
              [ 2  6  0]]

             [[ 5  1  6]
              [ 8  7  1]
              [ 5  1  3]]])

row_mean =

14.Compute the standard deviation of each column of the matrix a.


15.Compute the matrix multiplication of a with its transpose.


16.Create a 2D NumPy array c with dimensions 6x6 and values 1 in the diagonal and 0 elsewhere. Use the np.roll() function to shift the values in each row to the right by one position.


17.Create a 2D NumPy array d with dimensions 4x4 and random values between 0 and 1. Normalize the values in each row to have a sum of 1.


18.Create a 2D NumPy array e with dimensions 3x3 and values 1 through 9. Use the np.flipud() function to flip the matrix vertically.


19.Create a 2D NumPy array f with dimensions 4x4 and random integer values between 0 and 10. Sort the values in each row in ascending order.


20.Create a 2D NumPy array g with dimensions 5x5 and values 0 in the diagonal and 1 elsewhere. Use the np.linalg.inv() function to compute the inverse of the matrix.
