1.Create a NumPy array a with values 1 through 9. Reshape the array to a 3x3 matrix.


In [2]:
import numpy as np
a = np.arange(1,10)
print(a.reshape(3,3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


 2.Create a NumPy array b with values 5 through 13. Reshape the array to a 3x3 matrix. 

In [3]:
import numpy as np
b= np.arange(5,14)
print(b.reshape(3,3))

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


3.Multiply the matrix a by the matrix b using the @ operator. 

In [4]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b= np.array([[5,6,7],
             [ 8,9,10],
             [11,12,13]])

result = a @ b
print(result)

[[ 54  60  66]
 [126 141 156]
 [198 222 246]]


4.Compute the dot product of the first row of a with the first column of b.

In [5]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b= np.array([[5,6,7],
             [ 8,9,10],
             [11,12,13]])
first_row_a =a[0,:]
first_colomn_b = b[:,0]
dot_product = np.dot(first_row_a,first_colomn_b )
print(dot_product)

54


 5.Compute the sum of all the elements in the matrix a. 

In [9]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
result = np.sum(a)
print(result)

45


6.Compute the product of all the elements in the matrix b. 

In [11]:

b= np.array([[5,6,7],
             [ 8,9,10],
             [11,12,13]])

result =np.prod(b)
print(result)

259459200


7.Create a 1D NumPy array c with values [1, 2, 3, 4, 5]. Use the np.insert() function to insert the value 0 at index 2.

In [17]:
c = np.array( [1, 2, 3, 4, 5])
c = np.insert(c,2,0)
print(c)

[1 2 0 3 4 5]


 8.Create a 1D NumPy array d with values [1, 2, 3, 4, 5]. Use the np.delete() function to delete the value at index 3.

In [19]:
d = np.array( [1, 2, 3, 4, 5])
d = np.delete(c,3)
print(d)

[1 2 0 4 5]


 9.Create a 2D NumPy array e with dimensions 3x4 and values 1 through 12. Use boolean indexing to select all elements greater than 5. 

In [24]:
e = np.arange(1,13).reshape(3,4)

five_up = (e > 5) | (e == 5)
print(five_up)


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


10.Create a 2D NumPy array f with dimensions 4x5 and values 1 through 20. Use fancy indexing to select the elements at positions (0,0), (1,2), and (2,4). 

In [26]:
f= np.arange(1,21).reshape(4,5)

elements = f[[0,1,2],[0,2,4]]

print(f"Array f:\n{f}")
print(f"Selected elements: {elements}")

Array f:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Selected elements: [ 1  8 15]


11.Create a 2D NumPy array a with dimensions 5x5 and values 0.5 in the diagonal and 0 elsewhere.

In [10]:
a= np.eye(5)*0.5
print(a)

[[0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5]]


12.Create a 3D NumPy array b with dimensions 3x3x3 and random integer values between 0 and 10.


In [5]:
b = np.random.randint(0,11,size = (3,3,3))
print(b)

[[[ 9  0  9]
  [ 0  8  6]
  [ 5  5  5]]

 [[ 1  8  6]
  [10  9  7]
  [ 9  9  7]]

 [[ 8  9  8]
  [ 1  3 10]
  [ 7 10  6]]]


13.Compute the mean of each row of the matrix b.


In [8]:
import numpy as np
print(b)
print(" mean of each row of the matrix b")
row_mean =np.mean(b,axis = 1)
print(row_mean)

[[[ 9  0  9]
  [ 0  8  6]
  [ 5  5  5]]

 [[ 1  8  6]
  [10  9  7]
  [ 9  9  7]]

 [[ 8  9  8]
  [ 1  3 10]
  [ 7 10  6]]]
 mean of each row of the matrix b
[[4.66666667 4.33333333 6.66666667]
 [6.66666667 8.66666667 6.66666667]
 [5.33333333 7.33333333 8.        ]]


14.Compute the standard deviation of each column of the matrix a.


In [11]:
print(a)

column_std = np.std(a,axis=0)
print(" standard deviation of each column of the matrix a.")
print(column_std)

[[0.5 0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.5]]
 standard deviation of each column of the matrix a.
[0.2 0.2 0.2 0.2 0.2]


15.Compute the matrix multiplication of a with its transpose.


In [13]:
import numpy as np

trans_a = a.T
result =np.dot(a,trans_a)
print("matrix multiplication of a with its transpose:")
print(result)

matrix multiplication of a with its transpose:
[[0.25 0.   0.   0.   0.  ]
 [0.   0.25 0.   0.   0.  ]
 [0.   0.   0.25 0.   0.  ]
 [0.   0.   0.   0.25 0.  ]
 [0.   0.   0.   0.   0.25]]


16.Create a 2D NumPy array c with dimensions 6x6 and values 1 in the diagonal and 0 elsewhere. Use the np.roll() function to shift the values in each row to the right by one position.


In [19]:
c= np.eye(6)*1
print(c)
print("========================")
print("the shifted 2D array is :")
result = np.roll(a,shift=1,axis=1)
print(result)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
the shifted 2D array is :
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0.]]


17.Create a 2D NumPy array d with dimensions 4x4 and random values between 0 and 1. Normalize the values in each row to have a sum of 1.


In [25]:
d = np.random.rand(4,4)
print(d)
print("===================")
normalized_d = d /d.sum(axis = 1,keepdims=True)
print("normalized d is:")
print(normalized_d)

[[0.68361571 0.62654069 0.92049889 0.2131012 ]
 [0.45957904 0.22919826 0.45361636 0.25866441]
 [0.08908947 0.70364074 0.29363751 0.94256698]
 [0.92739533 0.55323851 0.5769299  0.40226337]]
normalized d is:
[[0.2797397  0.25638425 0.37667374 0.08720231]
 [0.32802283 0.16358941 0.32376699 0.18462077]
 [0.04390948 0.34680305 0.14472497 0.4645625 ]
 [0.37701647 0.22490951 0.23454083 0.16353319]]


18.Create a 2D NumPy array e with dimensions 3x3 and values 1 through 9. Use the np.flipud() function to flip the matrix vertically.


In [35]:
e = np.arange(1,10).reshape(3,3)
print(e)
fliped_e = np.flipud(e)
print("=============")
print(fliped_e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


19.Create a 2D NumPy array f with dimensions 4x4 and random integer values between 0 and 10. Sort the values in each row in ascending order.


In [44]:
f = np.random.randint(0,11,size=(4,4))
print(f)
print("===========================")
print("the sorted array is:")
ascent_f = np.sort(f,axis=1)
print(ascent_f)

[[ 0  0  7  6]
 [10  3 10  3]
 [10  8  1  5]
 [ 0  9 10  4]]
the sorted array is:
[[ 0  0  6  7]
 [ 3  3 10 10]
 [ 1  5  8 10]
 [ 0  4  9 10]]


20.Create a 2D NumPy array g with dimensions 5x5 and values 0 in the diagonal and 1 elsewhere. Use the np.linalg.inv() function to compute the inverse of the matrix.


In [51]:
g = np.eye(5)*1
g= 1-g
print(g)

print("=====================")
inverse_a = np.linalg.inv(g)
print(inverse_a)


[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]
[[-0.75  0.25  0.25  0.25  0.25]
 [ 0.25 -0.75  0.25  0.25  0.25]
 [ 0.25  0.25 -0.75  0.25  0.25]
 [ 0.25  0.25  0.25 -0.75  0.25]
 [ 0.25  0.25  0.25  0.25 -0.75]]
